import openingScreen from "./openingScreen/openingScreen";
import logIn from "./logIn/logIn";
import darkMode from "./darkMode/darkMode";
import lightMode from "./lightMode/lightMode";
import backButton from "./backButton/backButton";
import checkingForHandFeature from "./featureMenu/checkingHand/checkHand";
import participantRaiseHandSession from "./participant/participantHand/raiseAHandSession";
import speakerRaiseHandPreHand from "./speaker/speakerHand/raiseAHandSessionPreHand";
import speakerRaiseHandAfterHand from "./speaker/speakerHand/raiseAHandSessionAfterHand";
import logOut from "./logOut/logOut";

openingScreen();
logIn("speakerview@gmail.com", "(callbackCats)");
darkMode();
lightMode();
darkMode();
speakerRaiseHandPreHand();
logOut();
logIn("participantview@gmail.com", "(callbackCats)");
darkMode();
lightMode();
darkMode();
checkingForHandFeature();
participantRaiseHandSession();
backButton();
logOut();
logIn("speakerview@gmail.com", "(callbackCats)");
darkMode();
checkingForHandFeature();
speakerRaiseHandAfterHand();
backButton();
logOut();
